package dao;

public class Sentencias {
	public static String USER_POR_PK = "SELECT USUARIO, NOMBRE, APELLIDO, CORREO, EDAD, CONTRASENA FROM USUARIO WHERE USUARIO = ?";
	public static String USER_TICKET = "SELECT E.USUARIO, E.NUM_SALA, E.ID_PELICULA, P.TITULO, E.PRECIO, E.FECHA_ADQUIERE, E.FECHA_TRANSMISION FROM ENTRADA E JOIN PELICULA P ON E.ID_PELICULA = P.ID_PELICULA WHERE E.USUARIO = ?";
}
